# Generated by Django 2.0.5 on 2018-09-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadTrack',
            new_name='AddLeads',
        ),
    ]
