# Generated by Django 2.0.5 on 2018-09-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0002_auto_20180910_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addleads',
            name='YOP',
            field=models.IntegerField(),
        ),
    ]
